apiVersion: apps/v1
kind: Deployment
metadata:
  name: editable-blog
  annotations:
    secrets.infisical.com/auto-reload: 'true'
  labels:
    "monitor.bnei.dev/enabled": "true"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: editable-blog
  template:
    metadata:
      labels:
        app: editable-blog
    spec:
      containers:
        - image: mohammaddocker/editable-blog
          name: editable-blog
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: managed-editable-blog-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
