apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editable-website

resources:
- deployment.yml
- service.yml

images:
- name: mohammaddocker/editable-website
  newTag: 0.2.1
